---

- name: Download Nextcloud
  git:
    repo: '{{ nc_git_url }}'
    dest: '/home/{{ nc_user }}/public_html'
    version: master
    update: no
  when: not nextcloud_installed or nextcloud_installed is undefined

- name: Set correct permissions on document_root
  file:
    path: '/home/{{ nc_user }}/public_html'
    owner: '{{ nc_user }}'
    group: '{{ nc_user }}'
    recurse: yes

- name: Install Nextcloud
  become: true
  become_user: '{{ nc_user }}'
  command: |
    php occ maintenance:install --database "mysql"
    --database-name "{{ nc_mysql_database }}"  --database-user "{{ nc_mysql_username }}" --database-pass "{{ nc_mysql_password }}"
    --admin-user "{{ nc_nextcloud_admin_user }}" --admin-pass "{{ nc_nextcloud_admin_password }}"
  args:
    chdir: '/home/{{ nc_user }}/public_html/'
  when: not nextcloud_installed or nextcloud_installed is undefined

- name: Add our domain as trusted_domain in Nextcloud installation
  become: true
  become_user: '{{ nc_user }}'
  command: 'php occ config:system:set trusted_domains 1 --value={{ nc_domain }}'
  args:
    chdir: '/home/{{ nc_user }}/public_html/'
  when: not nextcloud_installed or nextcloud_installed is undefined

