---

- include: check-if-installed.yml
- include: pre-requisites.yml
- include: setup-users.yml
- include: database.yml
- include: install-nextcloud.yml
- include: tune-nextcloud.yml
- include: security-nextcloud.yml
