---

- name: Create users for nextcloud
  user:
    name: '{{ nc_user }}'
    home: '/home/{{ nc_user }}'
  loop: '{{ websites }}'  

- name: Create Nextcloud home directory
  file:
    path: '/home/{{ nc_user }}/public_html'
    owner: '{{ nc_user }}'
    group: '{{ nc_user }}'
    state: directory

- name: Set correct permissions on user's home directory
  file:
    path: '/home/{{ nc_user }}'
    mode: 0755
