---

- name: Tune php.ini
  ini_file:
    path: /etc/php.ini
    section: 'PHP'
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: '{{ nc_php_ini | dict2items }}'
  notify: Restart PHP-FPM

- name: Tune PHP opcache
  ini_file:
    path: '/etc/php.d/opcache.ini'
    section: ''
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: '{{ nc_php_opcache | dict2items }}'
  notify: Restart PHP-FPM

- name: Enable Redis as caching system
  become: true
  become_user: '{{ nc_user }}'
  command: '{{ item }}'
  args:
    chdir: '/home/{{ nc_user }}/public_html/'
  loop:
    - 'php occ config:system:set redis host --value="{{ nc_redis_host }}"'
    - 'php occ config:system:set redis port --value="{{ nc_redis_port }}"'
    - 'php occ config:system:set redis dbindex --value=0'
    - 'php occ config:system:set redis timeout --value=1.5'
    - 'php occ config:system:set memcache.locking --value="\OC\Memcache\Redis"'
  when: nc_redis_host is defined and nc_redis_port is defined and not nextcloud_installed or nextcloud_installed is undefined
