---

- name: Check if Nextcloud is already installed
  stat:
    path: '/home/{{ nc_user }}/public_html/index.php'
  register: nextcloud_installed_index

- set_fact:
    nextcloud_installed: yes
  when: nextcloud_installed_index.stat.exists
