---

- name: Create MySQL database
  mysql_db:
    name: '{{ nc_mysql_database }}'
    state: present

- name: Create MySQL user
  mysql_user:
    name: '{{ nc_mysql_username }}'
    password: '{{ nc_mysql_password }}'
    state: present
    host: 'localhost'
    priv: '{{ nc_mysql_database }}.*:ALL'
