---

- name: Check if new datadir already exists
  stat:
    path: '{{ nc_nextcloud_datadir }}'
  register: new_datadir

- name: Modify Nexcloud config in order to set new datadir
  become: true
  become_user: '{{ nc_user }}'
  command: 'php occ config:system:set datadirectory --value="{{ nc_nextcloud_datadir }}"'
  args:
    chdir: '/home/{{ nc_user }}/public_html/'
  when: not new_datadir.stat.exists

- name: Move default Nexcloud datadir
  copy:
    src: '/home/{{ nc_user }}/public_html/data/'
    dest: '{{ nc_nextcloud_datadir }}'
    owner: '{{ nc_user }}'
    group: '{{ nc_user }}'
    remote_src: yes
  when: not new_datadir.stat.exists

- name: Delete previous datadir
  file:
    path: '/home/{{ nc_user }}/public_html/data'
    state: absent
  when: not new_datadir.stat.exists
